Child Outcomes Summary  -Error We encountered an unexpected error. Please report the error to customer support.
c:\inetpub\wwwroot\DEV\IEP\Views\Form\ChildOutcomesSummary.cshtml(207): error CS0103: The name 'imageChecked' does not exist in the current context